development:
  adapter: postgresql
  database: nathan_development
  encoding: unicode
  user: spree2
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: nathan_test
  encoding: unicode
  user: spree2
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nathan_production
  encoding: unicode
  pool: 5
  timeout: 5000